security.oauth2.resource.filter-order: 3

security.signing-key: MaYzkSjmkzPC57L
security.encoding-strength: 53
security.security-realm: Spring Boot JWT Example Realm

security.jwt.client-id: testjwtclientid
security.jwt.client-secret: XY7kmzoNzl100
security.jwt.grant-type: password
security.jwt.scope-read: read
security.jwt.scope-write: write
security.jwt.resource-ids: testjwtresourceid

server.port: 8081
pageable.size: 10

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        show_sql: true
        format_sql: true
        hibernate.hbm2ddl.import_files: import.sql
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3310/houses
    username: houses
    password: houses