version: "3"
services:
  frontend:
    build: frontend
    ports:
     - 4200:80
  backend:
    build: backend
    ports:
     - 8081:8081
    links:
     - mysql
  mysql:
   image: mysql:8.0
   restart: always
   container_name: db-mysql
   ports:
    - 3310:3306
   environment:
     MYSQL_DATABASE: houses
     MYSQL_ROOT_PASSWORD: houses
     MYSQL_USER: houses
     MYSQL_PASSWORD: houses
     
